// Code generated by "stringer -type=CardValue"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Six-0]
	_ = x[Seven-1]
	_ = x[Eight-2]
	_ = x[Nine-3]
	_ = x[Banner-4]
	_ = x[Under-5]
	_ = x[Ober-6]
	_ = x[King-7]
	_ = x[Ace-8]
}

const _CardValue_name = "SixSevenEightNineBannerUnderOberKingAce"

var _CardValue_index = [...]uint8{0, 3, 8, 13, 17, 23, 28, 32, 36, 39}

func (i CardValue) String() string {
	if i < 0 || i >= CardValue(len(_CardValue_index)-1) {
		return "CardValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardValue_name[_CardValue_index[i]:_CardValue_index[i+1]]
}
