// Code generated by "stringer -type=Suit"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Schellen-0]
	_ = x[Rosen-1]
	_ = x[Schilten-2]
	_ = x[Eichel-3]
}

const _Suit_name = "SchellenRosenSchiltenEichel"

var _Suit_index = [...]uint8{0, 8, 13, 21, 27}

func (i Suit) String() string {
	if i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
